server:
  port: 8072
spring:
  cloud:
    gateway:
      #자동 routes
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #수동 routes
      routes:
      - id: test-service
        uri: http://localhost:8088
        predicates:
        - Path=/test-service/**
        filters:
        - RewritePath=/test-service/?(?<remaining>.*), /$\{remaining}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true